package interpreter.bytecodes.debuggerByteCodes;

import interpreter.VirtualMachine;
import interpreter.bytecodes.ByteCode;
import interpreter.debugger.DebugVirtualMachine;
import java.util.Vector;

/**
 * LINE n - n is the current source line number; the generated bytecodes
 * for line n follow this LINE n code
 */
public class LineCode extends ByteCode{
    private int lineNum;
    
    @Override
    public void init(Vector<String> args){
        lineNum = Integer.parseInt(args.get(0));       
    }
    
    @Override
    public void execute(VirtualMachine vm) {
        DebugVirtualMachine dvm = (DebugVirtualMachine) vm;
        dvm.line(lineNum);   
    }

    public int getLineNum() {
        return lineNum;
    }
}
